# Generated by Django 3.0.7 on 2020-07-06 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=254)),
                ('department', models.CharField(choices=[('CSE', 'COMPUTER SCIENCE ENGINEERING'), ('ECE', 'ELECTRONICS AND COMMUNICATION ENGINEERING')], default='CSE', max_length=254)),
                ('rollnum', models.IntegerField(unique=True)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=254)),
                ('department', models.CharField(choices=[('CSE', 'COMPUTER SCIENCE ENGINEERING'), ('ECE', 'ELECTRONICS AND COMMUNICATION ENGINEERING')], default='CSE', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
