# Generated by Django 3.0.7 on 2020-07-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'model',
            },
        ),
        migrations.AddField(
            model_name='userprofilestudent',
            name='def_pass_changed',
            field=models.BooleanField(default=False),
        ),
    ]
