# Generated by Django 3.0.6 on 2020-05-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilefaculty',
            name='department',
            field=models.CharField(choices=[('CSE', 'COMPUTER SCIENCE ENGINEERING'), ('ECE', 'ELECTRONICS AND COMMUNICATION ENGINEERING')], default='CSE', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofilestudent',
            name='department',
            field=models.CharField(choices=[('CSE', 'COMPUTER SCIENCE ENGINEERING'), ('ECE', 'ELECTRONICS AND COMMUNICATION ENGINEERING')], default='CSE', max_length=254),
        ),
    ]
