# Generated by Django 3.0.7 on 2020-07-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulthistory',
            name='exam_type',
            field=models.CharField(default='quiz-1', max_length=254),
            preserve_default=False,
        ),
    ]
