# Generated by Django 3.0.7 on 2020-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_instructor'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
