# Generated by Django 3.0.7 on 2020-06-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_searchable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchable',
        ),
    ]
