# Generated by Django 3.0.7 on 2020-07-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_approvedregistrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedregistrations',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1),
        ),
    ]
