# Generated by Django 3.0.7 on 2020-07-06 11:16

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=10, unique=True, verbose_name='Course ID')),
                ('name', models.CharField(max_length=254)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('instructor', models.ForeignKey(on_delete=models.SET(courses.models.get_sentinel_user), to='users.UserProfileFaculty')),
            ],
        ),
    ]
