# Generated by Django 3.0.6 on 2020-05-31 17:17

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200528_0036'),
        ('courses', '0002_auto_20200531_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=0, on_delete=models.SET(courses.models.get_sentinel_user), to='users.UserProfileFaculty'),
            preserve_default=False,
        ),
    ]
